__all__ = [
    "WALL_THICKNESS",
    "COURT_LENGTH",
    "WALL_HEIGHT",
    "COURT_WIDTH",
    "BACK_WALL_OUT_LINE_HEIGHT",
    "TIN_HEIGHT",
    "LINE_MARKING_WIDTH",
    "PAINT_THICKNESS",
    "FRONT_WALL_OUT_LINE_HEIGHT",
    "PLAYER_HEIGHT",
    "SERVICE_LINE_HEIGHT",
]

# All measurements in meters
WALL_THICKNESS = 0.03
COURT_LENGTH = 9.75
WALL_HEIGHT = 5.64
COURT_WIDTH = 6.4
BACK_WALL_OUT_LINE_HEIGHT = 2.13
SERVICE_LINE_HEIGHT = 1.78
TIN_HEIGHT = 0.43
LINE_MARKING_WIDTH = 0.05
PAINT_THICKNESS = 0.0001
FRONT_WALL_OUT_LINE_HEIGHT = 4.57
PLAYER_HEIGHT = 1.6
